//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RealtimeReviwsTags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RealtimeReviwsTags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RealtimeReviwsTags", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string RealtimeReviewTag_0 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string RealtimeReviewTag_1 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice bed.
        /// </summary>
        internal static string RealtimeReviewTag_10 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string RealtimeReviewTag_11 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovated new.
        /// </summary>
        internal static string RealtimeReviewTag_12 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great amenities.
        /// </summary>
        internal static string RealtimeReviewTag_13 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacious.
        /// </summary>
        internal static string RealtimeReviewTag_14 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        internal static string RealtimeReviewTag_15 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Bathroom.
        /// </summary>
        internal static string RealtimeReviewTag_16 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible bed.
        /// </summary>
        internal static string RealtimeReviewTag_17 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty.
        /// </summary>
        internal static string RealtimeReviewTag_18 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old, outdated.
        /// </summary>
        internal static string RealtimeReviewTag_19 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string RealtimeReviewTag_2 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Few amenities.
        /// </summary>
        internal static string RealtimeReviewTag_20 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string RealtimeReviewTag_21 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noisy.
        /// </summary>
        internal static string RealtimeReviewTag_22 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Bathroom.
        /// </summary>
        internal static string RealtimeReviewTag_23 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        internal static string RealtimeReviewTag_24 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Shopping.
        /// </summary>
        internal static string RealtimeReviewTag_25 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good eats.
        /// </summary>
        internal static string RealtimeReviewTag_26 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        internal static string RealtimeReviewTag_27 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkable.
        /// </summary>
        internal static string RealtimeReviewTag_28 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy parking.
        /// </summary>
        internal static string RealtimeReviewTag_29 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        internal static string RealtimeReviewTag_3 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous.
        /// </summary>
        internal static string RealtimeReviewTag_30 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dining.
        /// </summary>
        internal static string RealtimeReviewTag_31 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transportation.
        /// </summary>
        internal static string RealtimeReviewTag_32 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run-down.
        /// </summary>
        internal static string RealtimeReviewTag_33 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parking.
        /// </summary>
        internal static string RealtimeReviewTag_34 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string RealtimeReviewTag_4 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome gift.
        /// </summary>
        internal static string RealtimeReviewTag_5 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with reservation.
        /// </summary>
        internal static string RealtimeReviewTag_6 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string RealtimeReviewTag_7 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected fees.
        /// </summary>
        internal static string RealtimeReviewTag_8 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No perks.
        /// </summary>
        internal static string RealtimeReviewTag_9 {
            get {
                return ResourceManager.GetString("RealtimeReviewTag_9", resourceCulture);
            }
        }
    }
}
